### ISSUE TITLE
Reduce exported symbols

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#11]
Should we export as many symbols as possible or export only a minimum number of symbols?

https://github.com/SpM-lab/SparseIR.jl/blob/main/src/SparseIR.jl#L10-L19

**Comment by SamuelBadr** [comment]
Yes! I've been meaning to reduce the number of exports, but I wanted to ask you and @mwallerb first which ones you'd like to keep.

**Comment by mwallerb** [comment]
Agreed! I would vote for the symbols exported in the top namespace of sparse-ir (`DimensionlessBasis` ...)

**Comment by shinaoka** [comment]
>I would vote for the symbols exported in the top namespace of sparse-ir (DimensionlessBasis ...)

What do you exactly mean?

**Comment by SamuelBadr** [comment]
I reduced it a bit in https://github.com/SpM-lab/SparseIR.jl/commit/fc4aa3b1cd2d59798ac2f04f05d4340cffa6b1eb, it now looks like this:
```julia
export fermion, boson
export DimensionlessBasis, FiniteTempBasis, finite_temp_bases
export SparsePoleRepresentation, to_IR, from_IR
export overlap
export LegendreBasis, MatsubaraConstBasis
export FiniteTempBasisSet
export LogisticKernel, RegularizedBoseKernel
export CompositeBasis, CompositeBasisFunction, CompositeBasisFunctionFT
export TauSampling, MatsubaraSampling, evaluate, fit
```
Still feels a bit much, doesn't it? IDK what we want to drop though.

**Comment by shinaoka** [comment]
Thank you! Looks nice
