### ISSUE TITLE
Bug for SVD with Double64

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#12]
A minimum code:

```
using SparseIR
FiniteTempBasis(fermion, 1.0, 1.0, 1e-10)
```

Error message:
![image](https://user-images.githubusercontent.com/15949860/168545875-67d93646-574b-4df8-a890-da3075ef97a8.png)

I think the kernel must be initialized with Double64 when the cutoff is small. Alternatively, we could always use Double64 for the kernel for safety.

**Comment by mwallerb** [comment]
Yes, this is crucial! The kernel **must** be computed with Double64 if we want full accuracy!

**Comment by SamuelBadr** [comment]
Woah github closed this automagically as soon as I pushed my commit with `fix #12` in the commit message. Didn't know this was a thing!
