### ISSUE TITLE
Add `evaluate!` and `fit!`

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#19]
Just a memo
To avoid allocating a new array, implementing them may be useful.
But, if dim!=1 and dim!=end, we still need to allocate temporary arrays for permutating dims.

**Comment by SamuelBadr** [comment]
I'll implement 3 argument-versions of both, akin to `mul!`.

**Comment by SamuelBadr** [comment]
In benchmarking `mul!` and `*` at the matrix sizes relevant to us (< 200 x 200) the latter seems to be only marginally slower and allocates only a couple of bytes. Not sure there is much benefit to be had from implementing this.

Opinions?

**Comment by shinaoka** [comment]
Thank you for the information. What did you benchmark exactly?

**Comment by shinaoka** [comment]
One main bottleneck in FLEX calculations is memory. The current implementation of `fit` allocates a temporary array for work space and returns the result as a new array.

**Comment by SamuelBadr** [comment]
> Thank you for the information. What did you benchmark exactly?
<img width="739" alt="Screenshot 2022-05-25 at 09 30 20" src="https://user-images.githubusercontent.com/4489583/170206082-29494e16-3431-4ca8-8bd2-e7f44988f3f2.png">

**Comment by shinaoka** [comment]
In our case, `b` is a rectangular matrix of size (m, N), where N could be huge. N is the product of the dimensions of the axes excluding the one specified by `dim`.

**Comment by SamuelBadr** [comment]
Ok, in that case (with `N = 10^4`) the time difference is still negligible, but `*` allocates a few MBs, so I'm guessing if you do this enough you hit GC. I understand now, thank you!

**Comment by shinaoka** [comment]
I now remember what I did before.

My old experiment revealed that `mapslice` allocates a lot.
If `*` allocate only a few MB, either `mul!` or `*` may be fine.
