### ISSUE TITLE
Composite/augmented basis issues

### ISSUE THREAD

**Issue by mwallerb** [SpM-lab/SparseIR.jl#35]
The composite/augmented basis things are in a pretty sorry state right now.

Problems:

 - there is essentially no documentation on how and why to use this
 - the interface is not type-stable *at all*, it stores a bunch of `Vector{Any}` and `Union{...}` instead of doing this properly
 - the sampling points are incorrect!  composite basis does not actually augment the sampling points in any way, which completely wrecks any fitting procedure.

**Comment by shinaoka** [comment]
This is too Pythonic. 
CompositeBasis should be a parametric type at least.
But, how about `u` and `v`?

**Comment by SamuelBadr** [comment]
Fixed in https://github.com/SpM-lab/SparseIR.jl/pull/37.
