### ISSUE TITLE
Adjust Twork for small ε

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#4]
```
lambda_ = 100.0
beta = 10.0
wmax = lambda_/beta
basis = FiniteTempBasis(fermion, beta, wmax, 1e-10)
```

yields

<img width="719" alt="image" src="https://user-images.githubusercontent.com/15949860/165277225-e1b6e944-5235-40a4-8cc2-16a9c501cefe.png">

**Comment by SamuelBadr** [comment]
This depends on https://github.com/JuliaLinearAlgebra/TSVD.jl/issues/33. The other option is porting the Python code.

**Comment by SamuelBadr** [comment]
Thanks to @mwallerb's outstanding work in https://github.com/SpM-lab/SparseIR.jl/pull/7, this now works as it should!
