### ISSUE TITLE
Delay SVD of the transformation matrix in `TauSampling` and `MatsubaraSampling`

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#49]
The SVD can be done when the `fit` is called first time.

**Comment by SamuelBadr** [comment]
I implemented this in the lazy-svd branch but had to make the `*Sampling` types mutable, so I'm a little hesitant to merge into main. If it degrades performance, maybe the current solution (specifying `factorize = false` via kwarg in the `*Sampling` constructors) is preferable. What do you think?

**Comment by shinaoka** [comment]
> maybe the current solution (specifying factorize = false via kwarg in the *Sampling constructors) is preferable.

Sorry, I was not aware of this change!
OK, let us stick to your solution.

BTW, we should add some description on this point in the "sparse-ir-tutorial" since this is crucial when evaluating an object on a large number of frequencies and tau points.
