### ISSUE TITLE
Implement tests for poly.jl that are independent from sve.jl

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#51]

**Comment by shinaoka** [comment]
TODO
* Implement tests for `overlap`, `deriv`, `roots`
* Implement tests for ` PiecewiseLegendrePolyVector`

**Comment by terasakisatoshi** [comment]
Tests for the `overlap` function can be found at:

https://github.com/SpM-lab/SparseIR.jl/blob/7eabaa9b9f5cb8f6a1bd4eb9a4e4f89907aa4039/test/poly.jl#L59-L61

**Comment by terasakisatoshi** [comment]
Sorry, I missed the title > independent from sve.jl

**Comment by terasakisatoshi** [comment]
I'm working on it > Implement tests for overlap, deriv, roots
