### ISSUE TITLE
Perfomance of evaluating uhat

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#6]
This performance problem becomes serious when evaluating the basis functions on a dense frequency mesh.

Julia:
```
using SparseIR
beta = 1.0
wmax = 1000.0
basis = FiniteTempBasis(fermion, beta, wmax, 1e-7)
nvec = 2 .* collect(1:10000) .+ 1
basis.uhat(nvec)
@time basis.uhat(nvec)
```

```
22.467327 seconds (72.36 M allocations: 22.350 GiB, 6.70% gc time)
```

Python:
```
from sparse_ir import FiniteTempBasis
import numpy as np
import time
beta = 1.0
wmax = 1000.0
basis = FiniteTempBasis("F", beta, wmax, 1e-7)
nvec = 2 * np.arange(10000) + 1
t1 = time.time()
basis.uhat(nvec)
time.time() - t1
```

```
0.49092721939086914
```

**Comment by shinaoka** [comment]
Vectorizing the function w.r.t frequencies may alleviate the problem.

**Comment by mwallerb** [comment]
I think so.  The whole thing is dominated by the Bessel function evaluations ... which are however independent of `l`

**Comment by SamuelBadr** [comment]
> I think so. The whole thing is dominated by the Bessel function evaluations ... which are however independent of `l`

I did some profiling and found the same thing. I'm not clear on how to proceed though: `SpecialFunctions.jl` doesn't provide a `sphericalbesselj(n, x::Vector)` as far as I can tell, and this call is where most of the time is spent.

**Comment by mwallerb** [comment]
@Samuel3008  That's no problem ... let's discuss tomorrow!

**Comment by SamuelBadr** [comment]
Perfect, see you tomorrow!

**Comment by SamuelBadr** [comment]
https://github.com/SpM-lab/SparseIR.jl/commit/dfc8499535b9355275c98a92ebfc2899eb2ac06e

@shinaoka your example takes 1.2 seconds on my laptop now. Could you please try again on your machine and let me know?

**Comment by shinaoka** [comment]
Great work! It took only 0.8 seconds on my Macbook Pro M1.
