### ISSUE TITLE
Conflicting symbol names (`beta`)

### ISSUE THREAD

**Issue by shinaoka** [SpM-lab/SparseIR.jl#8]
@sakurairihito

We (I and R. Sakurai) found this bit annoying:

```
using SparseIR
lambda_ = 100.0
beta = 10.0
wmax = lambda_/beta
basis = FiniteTempBasis(fermion, beta, wmax, 1e-7)
println(beta(basis))
```

Many Julia users seem to prefer to using `using`.
We should rename the accessor something like `getbeta`?
The same applies to `wmax`...

**Comment by SamuelBadr** [comment]
I agree! I'll fix this later today.

**Comment by SamuelBadr** [comment]
Sorry I forgot to push. https://github.com/SpM-lab/SparseIR.jl/commit/13dcc2a7553e16f4e10cdc3244613d052dd32f3e
